name: Sync with Upstream

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:       # Allow manual run too

jobs:
  sync:
    name: Sync Repository
    runs-on: ubuntu-latest

    concurrency:
      group: sync-upstream
      cancel-in-progress: true

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/TheSpeedX/PROXY-List.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/master --allow-unrelated-histories -m "Auto-sync: upstream changes"
          git push origin master
