name: Sync with upstream

on:
  schedule:
    - cron: '0 */30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/TheSpeedX/PROXY-List.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories -m "Sync from upstream"
          git push origin master
